org: thepremiumcoder
app: serverless-sample-project-yml
service: 'serverless-sample-project-yml'
frameworkVersion: '3'

plugins:
  - serverless-esbuild
  
provider:
  name: 'aws'
  runtime: nodejs14.x
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'

functions: 
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get